Refactor to use javascript classes
berylcl/Awesome-books pull request #1
Opened 2023-04-24 17:59 UTC by berylcl

2023-04-24 18:17 UTC, Shisui6 reviewed
Hi @berylcl, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛠️

You have submitted a pair programming project with no commits from your coding partner. Please make sure that your coding partners commit to this project and submit again for review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-25 10:00 UTC, rloterh requested changes
Hi Kingsley & Gakii, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 
🚦 _ 🏡 🏃‍♂️ 🏚️ 🌴 🗼

## Highlights 👍  
- Objects properly refactored into classes!
- App is running correctly after refactoring!

## Required Changes ♻️
_Kindly check the inline comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

_Kindly check the inline comments marked **[OPTIONAL]** under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 10:00 UTC, rloterh commented on style.css
> +
Your app is working as intended 👌, however, in this activity, we want the UI design of this book app to closely match the given [wireframe](https://github.com/microverseinc/curriculum-javascript/blob/bb245ca8a9d3bb04ebefbbd45e800764e1fc5f74/books/images/awesome_books_core_elements.png). Let's, therefore, introduce the following improvements to our design:
- [ ] The _Add New Book_ form should be vertically center aligned with the _Books table_.

- [ ] The _Add_ button on the _Add New Books_ form should be aligned to the right with the input fields, as seen in the wireframe.

**Your design:**
![image](https://user-images.githubusercontent.com/12745474/234240404-dfd4d436-c2c0-47a4-95d6-071b0652ca39.png)

**Wireframe design:**
![image](https://user-images.githubusercontent.com/12745474/234240576-3ea2f7a2-4658-43c8-aa83-de5a9fa301cd.png)

2023-04-25 10:00 UTC, rloterh commented on README.md
> +
- [ ] [OPTIONAL]
Kindly include clear and step-by-step instructions in your ReadMe on how to _setup_ and _run_ your app, under the _Getting Started_ section. 
Implementing the above change(s) will make your ReadMe/ repository stand out even better! 😉

2023-04-25 10:45 UTC, julie-ify approved these changes
Hi @berylcl and @unorjikingsley,

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 10:46 UTC, merged